from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class ArgumentExtractionRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class Argument(BaseModel):
    party: str
    argument: str
    reasoning: str
    authorities: list[str]
    court_resolution: str


class GeneratedArguments(BaseModel):
    case_name: str
    petitioner: str
    respondent: str
    petitioner_arguments: list[Argument]
    respondent_arguments: list[Argument]
    counterarguments_considered: list[str]
    key_doctrines_statutes: list[str]
    winning_party: str
    rationale: str
    sources_consulted: list[str]


class ArgumentExtractionResponse(BaseModel):
    case_name: str
    petitioner: str
    respondent: str
    petitioner_arguments: list[Argument]
    respondent_arguments: list[Argument]
    counterarguments_considered: list[str]
    key_doctrines_statutes: list[str]
    winning_party: str
    rationale: str
    sources: list[SourceDocument] = []
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This argument analysis was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
