from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class BluebookFormatRequest(BaseModel):
    """One or more raw citations (one per line) to reformat per Bluebook rules."""

    text: str


class BluebookEntry(BaseModel):
    """A single formatted citation with the Bluebook rules that were applied."""

    raw_input: str
    formatted: str
    case_name: Optional[str] = None
    authority_type: str = "other"
    rules_applied: list[str] = []
    notes: str = ""
    confidence: str = "medium"
    from_local: bool = False


class GeneratedBluebookResult(BaseModel):
    """LLM structured output: entries for the citations it was asked to format."""

    entries: list[BluebookEntry]
    general_notes: str = ""
    sources_consulted: list[str] = []


class BluebookFormatResponse(BaseModel):
    entries: list[BluebookEntry]
    general_notes: str = ""
    sources: list[SourceDocument] = []
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This citation formatting was generated by AI for educational purposes only. "
        "It is not legal advice. Bluebook rules vary by jurisdiction and publisher; "
        "verify all citations against the current Bluebook before relying on them."
    )