from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class CaseBriefRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class GeneratedBrief(BaseModel):
    case_name: str
    citation: list[str]
    court: str
    date_filed: str
    facts: str
    procedural_history: str
    issues: list[str]
    holding: str
    reasoning: str
    rule_of_law: str
    concurrence: Optional[str] = None
    dissent: Optional[str] = None
    significance: str


class CaseBriefResponse(BaseModel):
    case_name: str
    citation: list[str]
    court: str
    date_filed: str
    facts: str
    procedural_history: str
    issues: list[str]
    holding: str
    reasoning: str
    rule_of_law: str
    concurrence: Optional[str] = None
    dissent: Optional[str] = None
    significance: str
    sources: list[SourceDocument] = []
    disclaimer: str = (
        "This case brief was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
