from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class CitationMapRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class CitedAuthority(BaseModel):
    name: str
    citation: Optional[str] = None
    type: str
    context: str
    treatment: str


class GeneratedCitationMap(BaseModel):
    case_name: str
    cases_cited: list[CitedAuthority]
    statutes_cited: list[CitedAuthority]
    constitutional_provisions: list[CitedAuthority]
    total_citations: int
    key_precedent: str
    sources_consulted: list[str]


class CitationMapResponse(BaseModel):
    case_name: str
    cases_cited: list[CitedAuthority]
    statutes_cited: list[CitedAuthority]
    constitutional_provisions: list[CitedAuthority]
    total_citations: int
    key_precedent: str
    sources: list[SourceDocument] = []
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This citation analysis was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all citations with primary sources."
    )
