from pydantic import BaseModel
from typing import Optional


class CaseCompareRequest(BaseModel):
    """Exactly two landmark case names to compare."""

    case_names: list[str]


class CompareCaseFacts(BaseModel):
    """Static, curated facts for one case (no LLM involved)."""

    name: str
    citation: str
    year: int
    court: str
    date_filed: str
    subjects: list[str]
    holdings: list[str]


class CaseComparison(BaseModel):
    """LLM-generated comparison of the two cases."""

    similarities: list[str]
    differences: list[str]
    relationship: str
    relationship_type: str
    significance: str
    practice_note: str


class CaseCompareResponse(BaseModel):
    case_a: CompareCaseFacts
    case_b: CompareCaseFacts
    comparison: Optional[CaseComparison] = None
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This case comparison was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all statements against the primary opinions."
    )