from pydantic import BaseModel
from typing import Optional


class DebateRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class DebateArgument(BaseModel):
    side: str
    title: str
    argument: str
    reasoning: str
    authorities: list[str]
    strength: str
    counter_rebuttal: Optional[str] = None


class GeneratedDebate(BaseModel):
    topic: str
    user_position: str
    supporting_arguments: list[DebateArgument]
    opposing_arguments: list[DebateArgument]
    key_doctrines_statutes: list[str]
    predicted_winner: str
    rationale: str
    practice_tips: list[str]


class DebateResponse(BaseModel):
    topic: str
    user_position: str
    supporting_arguments: list[DebateArgument]
    opposing_arguments: list[DebateArgument]
    key_doctrines_statutes: list[str]
    predicted_winner: str
    rationale: str
    practice_tips: list[str]
    source: str
    disclaimer: str = (
        "This debate analysis was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
