from pydantic import BaseModel
from typing import Optional


class GenerateDocumentRequest(BaseModel):
    template_name: str
    field_values: dict[str, str]
    title: Optional[str] = None


class GenerateDocumentResponse(BaseModel):
    id: int
    title: str
    content: str
    doc_type: str
    disclaimer: str = (
        "This document was generated by AI for educational purposes only. "
        "It should be reviewed by a qualified legal professional before use."
    )
