from pydantic import BaseModel
from typing import Optional, Any

from app.models.source import SourceDocument


class IssueSpotterRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class SpottedIssue(BaseModel):
    issue: str
    rule: str
    application: str
    conclusion: str
    missing_information: str
    relevant_authorities: list[str]


class GeneratedIssueSpotter(BaseModel):
    overview: str
    issues: list[SpottedIssue]
    issues_by_area: dict[str, list[str]]
    practice_tips: str
    sources_consulted: list[str]


class IssueSpotterResponse(BaseModel):
    overview: str
    issues: list[SpottedIssue]
    issues_by_area: dict[str, list[str]]
    practice_tips: str
    sources: list[SourceDocument] = []
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This issue-spotting analysis was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
