from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class GlossaryRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class GeneratedGlossaryEntry(BaseModel):
    term: str
    definition: str
    etymology: Optional[str] = None
    jurisdiction: Optional[str] = None
    usage_example: str
    related_terms: list[str]
    also_known_as: Optional[str] = None
    practice_tips: Optional[str] = None
    citations: list[str]


class GlossaryResponse(BaseModel):
    term: str
    definition: str
    etymology: Optional[str] = None
    jurisdiction: Optional[str] = None
    usage_example: str
    related_terms: list[str]
    also_known_as: Optional[str] = None
    practice_tips: Optional[str] = None
    citations: list[str]
    from_seed: bool = False
    source: str
    sources: list[SourceDocument] = []
    disclaimer: str = (
        "This glossary entry was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify definitions with primary legal sources."
    )
