from pydantic import BaseModel
from typing import Optional


class LegalSummaryRequest(BaseModel):
    query: str
    summary_type: Optional[str] = "general"
    document_id: Optional[int] = None


class GeneratedSummary(BaseModel):
    title: str
    overview: str
    key_findings: list[str]
    legal_principles: list[str]
    impact: str
    key_points: list[str]
    sources_consulted: list[str]


class LegalSummaryResponse(BaseModel):
    title: str
    summary_type: str
    overview: str
    key_findings: list[str]
    legal_principles: list[str]
    impact: str
    key_points: list[str]
    sources_consulted: list[str]
    source: str
    disclaimer: str = (
        "This legal summary was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
