from pydantic import BaseModel
from typing import Optional

from app.models.source import SourceDocument


class LegalIssue(BaseModel):
    issue: str
    rule: str
    application: str
    conclusion: str


class MemorandumRequest(BaseModel):
    query: str
    document_id: Optional[int] = None


class GeneratedMemorandum(BaseModel):
    to: str
    author: str
    date: str
    re: str
    question_presented: str
    brief_answer: str
    facts: str
    issues: list[LegalIssue]
    overall_conclusion: str
    sources_consulted: list[str]


class MemorandumResponse(BaseModel):
    to: str
    author: str
    date: str
    re: str
    question_presented: str
    brief_answer: str
    facts: str
    issues: list[LegalIssue]
    overall_conclusion: str
    sources: list[SourceDocument] = []
    sources_consulted: list[str] = []
    disclaimer: str = (
        "This memorandum was generated by AI for educational purposes only. "
        "It should not be relied upon as legal advice. "
        "Users should verify all legal conclusions with primary sources."
    )
