"""Case comparison service for the Doctrine Explorer.

Compares any two of the 85 landmark cases. Static facts (citation, year,
subjects, holdings) come from curated data with zero LLM cost; the narrative
comparison is generated by the LLM from the offline seed opinions, so no
CourtListener calls are needed.
"""
import json
import logging
import os
from pathlib import Path
from typing import Optional

from litellm import completion

from app.ingest_landmark_cases import LANDMARK_CASES
from app.models.compare import (
    CaseCompareRequest,
    CaseCompareResponse,
    CompareCaseFacts,
    CaseComparison,
)
from app.services.doctrine_map import get_doctrine_map
from app.services.llm_errors import friendly_llm_error
from app.services.retrieval import parse_llm_json
from app.services.document_saver import save_document

logger = logging.getLogger(__name__)

MODEL = "openrouter/qwen/qwen3-14b"
EXTRA_BODY = {"provider": {"order": ["cerebras"]}}

SEED_PATH = Path(__file__).resolve().parent.parent / "data" / "landmark_seed.json"
MAX_OPINION_CHARS = 20000

SYSTEM_PROMPT = """You are a law professor helping law students compare landmark Supreme Court cases.

Given the names and opinion excerpts of two landmark cases, produce a structured comparison:

1. SIMILARITIES: 3-6 legal similarities (shared questions, doctrines, methods of analysis, or outcomes).
2. DIFFERENCES: 3-6 legal differences (facts, holding, reasoning, constitutional provisions, or outcome).
3. RELATIONSHIP: One or two sentences explaining how the two cases relate doctrinally — e.g. whether the later case overruled, distinguished, refined, applied, or was decided independently of the earlier one. Be precise about which case is later.
4. RELATIONSHIP_TYPE: one of "overruled", "distinguished", "refined", "applied", "independent", or "uncertain".
5. SIGNIFICANCE: What the pair teaches about how constitutional doctrine evolves.
6. PRACTICE_NOTE: An exam-writing tip — how a student could use both cases in the same essay (e.g. arguing a case is still good law, or distinguishing it on facts).

Rules:
- Base every claim ONLY on the provided opinion excerpts and your knowledge of the cited case. Do not fabricate holdings.
- If the provided text is truncated, note that in the significance field rather than guessing.
- Never present educational analysis as legal advice."""


def _build_user_prompt(case_a: dict, case_b: dict) -> str:
    return f"""Compare these two landmark cases.

## Case A: {case_a['name']} ({case_a['year']})
Opinion excerpt:
{case_a['text']}

## Case B: {case_b['name']} ({case_b['year']})
Opinion excerpt:
{case_b['text']}

Return the structured comparison in the required JSON format."""


def _load_seed() -> list[dict]:
    if not SEED_PATH.exists():
        logger.error("Landmark seed not found at %s", SEED_PATH)
        return []
    with open(SEED_PATH, encoding="utf-8") as f:
        return json.load(f)


SEED_CASES = _load_seed()


def _normalize(name: str) -> str:
    t = name.lower()
    for token in [" v. ", " v ", " vs. "]:
        t = t.replace(token, " v ")
    return " ".join(t.split())


def _find_case(name: str) -> Optional[dict]:
    key = _normalize(name)
    for case in LANDMARK_CASES:
        if _normalize(case["name"]) == key:
            return case
    matches = [
        c for c in LANDMARK_CASES
        if _normalize(c["name"]) in key or key in _normalize(c["name"])
    ]
    if len(matches) == 1:
        return matches[0]
    return None


def _seed_entry(name: str) -> Optional[dict]:
    key = _normalize(name)
    for entry in SEED_CASES:
        if _normalize(entry.get("name", "")) == key:
            return entry
    return None


def _facts_for(case: dict) -> CompareCaseFacts:
    seed = _seed_entry(case["name"])
    subjects: list[str] = []
    holdings: list[str] = []
    for doctrine in get_doctrine_map().get("doctrines", []):
        for node in doctrine.get("cases", []):
            if _normalize(node["name"]) == _normalize(case["name"]):
                subjects.append(doctrine["name"])
                if node.get("holding"):
                    holdings.append(node["holding"])
    court = (seed or {}).get("court") or "Supreme Court of the United States"
    date_filed = (seed or {}).get("date_filed", "")
    return CompareCaseFacts(
        name=case["name"],
        citation=case["citation"],
        year=case["year"],
        court=court,
        date_filed=date_filed,
        subjects=sorted(set(subjects)),
        holdings=holdings,
    )


def _opinion_text(name: str) -> str:
    seed = _seed_entry(name)
    if not seed:
        return ""
    text = seed.get("opinion_text", "")
    if len(text) > MAX_OPINION_CHARS:
        text = text[:MAX_OPINION_CHARS] + "\n[opinion excerpt truncated]"
    return text


def _to_markdown(facts_a: CompareCaseFacts, facts_b: CompareCaseFacts, comparison: CaseComparison) -> str:
    parts = [
        f"# Case Comparison: {facts_a.name} vs {facts_b.name}",
        "",
        "## Quick Facts",
        "",
        f"- **{facts_a.name}** ({facts_a.year}) — {facts_a.citation}",
        f"- **{facts_b.name}** ({facts_b.year}) — {facts_b.citation}",
        "",
        "## Similarities",
        "",
    ]
    for s in comparison.similarities:
        parts.append(f"- {s}")
    parts += ["", "## Differences", ""]
    for d in comparison.differences:
        parts.append(f"- {d}")
    parts += [
        "",
        "## Doctrinal Relationship",
        "",
        f"**{comparison.relationship_type}** — {comparison.relationship}",
        "",
        "## Significance",
        "",
        comparison.significance,
        "",
        "## Exam Practice Note",
        "",
        comparison.practice_note,
        "",
    ]
    return "\n".join(parts)


class CaseCompareService:
    def compare(self, request: CaseCompareRequest, user_id: Optional[int] = None) -> CaseCompareResponse:
        names = [n.strip() for n in (request.case_names or []) if n and n.strip()]
        if len(names) != 2:
            raise ValueError("Please select exactly two cases to compare.")
        if _normalize(names[0]) == _normalize(names[1]):
            raise ValueError("The two cases must be different.")

        case_a = _find_case(names[0])
        case_b = _find_case(names[1])
        if not case_a or not case_b:
            unknown = names[0] if not case_a else names[1]
            raise ValueError(
                f"Unknown landmark case: '{unknown}'. "
                "Only the 85 curated landmark cases can be compared."
            )

        facts_a = _facts_for(case_a)
        facts_b = _facts_for(case_b)

        text_a = _opinion_text(case_a["name"])
        text_b = _opinion_text(case_b["name"])
        if not text_a or not text_b:
            raise ValueError("Opinion text is unavailable for one of the selected cases.")

        try:
            response = completion(
                model=MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": _build_user_prompt(
                        {"name": case_a["name"], "year": case_a["year"], "text": text_a},
                        {"name": case_b["name"], "year": case_b["year"], "text": text_b},
                    )},
                ],
                response_format=CaseComparison,
                max_tokens=4000,
                temperature=0.3,
                reasoning_effort="low",
                drop_params=True,
                timeout=180,
            )
            raw = response.choices[0].message.content
            if raw is None:
                raw = getattr(response.choices[0].message, "reasoning_content", None) or ""
            parsed = parse_llm_json(raw)
            comparison = CaseComparison(**parsed)
        except Exception as e:
            logger.error(f"Case comparison generation failed: {e}")
            raise ValueError(f"Failed to compare cases: {friendly_llm_error(e)}")

        try:
            if user_id:
                md = _to_markdown(facts_a, facts_b, comparison)
                save_document(
                    user_id,
                    f"Case Comparison: {facts_a.name} vs {facts_b.name}",
                    md,
                    "case_comparison",
                )
        except Exception as e:
            logger.warning(f"Failed to save case comparison document: {e}")

        return CaseCompareResponse(
            case_a=facts_a,
            case_b=facts_b,
            comparison=comparison,
            sources_consulted=[
                case_a["name"],
                case_b["name"],
            ],
        )


case_compare_service = CaseCompareService()


def get_case_compare_service() -> CaseCompareService:
    return case_compare_service