from app.models.tutor import TutorQuestion

TOPICS = {
    "contracts": {
        "name": "Contracts",
        "description": "Formation, performance, and enforcement of legally binding agreements.",
        "questions": [
            TutorQuestion(
                question="What are the four essential elements required for a valid contract?",
                hint="Think about what makes a promise legally enforceable.",
                expected_concepts=["offer", "acceptance", "consideration", "mutual assent", "meeting of the minds"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is consideration in contract law? Explain with an example of valid consideration and one where consideration is lacking.",
                hint="Consider the difference between a bargained-for exchange and a gift.",
                expected_concepts=["bargained-for exchange", "legal detriment", "benefit", "adequacy vs sufficiency"],
                difficulty=2,
            ),
            TutorQuestion(
                question="Under the common law, when is an offer considered terminated before acceptance?",
                hint="Think about what circumstances can end the power of acceptance.",
                expected_concepts=["revocation", "rejection", "counteroffer", "lapse of time", "death or incapacity"],
                difficulty=2,
            ),
            TutorQuestion(
                question="Explain the difference between a bilateral contract and a unilateral contract. Provide an example of each.",
                hint="Focus on how acceptance is communicated in each type.",
                expected_concepts=["promise for a promise", "promise for an act", "acceptance by performance", "communication"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the Statute of Frauds and what types of contracts must be in writing to be enforceable?",
                hint="Consider contracts that are historically prone to fraud or misunderstanding.",
                expected_concepts=["writing requirement", "sale of land", "suretyship", "contracts lasting over one year", "goods over $500"],
                difficulty=3,
            ),
            TutorQuestion(
                question="When can a contract be voided due to a unilateral mistake? How does this differ from a mutual mistake?",
                hint="Consider the difference between both parties being wrong versus one party being wrong.",
                expected_concepts=["mutual mistake", "unilateral mistake", "material fact", "known or should have known", "risk allocation"],
                difficulty=4,
            ),
            TutorQuestion(
                question="Under the UCC versus common law, how are additional terms in an acceptance treated? What is the 'battle of the forms'?",
                hint="UCC 2-207 changes the common law 'mirror image' rule for sale of goods.",
                expected_concepts=["UCC 2-207", "additional terms", "mirror image rule", "merchant vs non-merchant", "conditional acceptance"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the doctrine of promissory estoppel and when can it be used as a substitute for consideration?",
                hint="This doctrine allows enforcement of promises even without consideration.",
                expected_concepts=["promissory estoppel", "reasonable reliance", "foreseeable reliance", "injustice prevention", "clear and definite promise"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the parol evidence rule and what are its exceptions?",
                hint="This rule limits the use of prior or contemporaneous evidence to vary contract terms.",
                expected_concepts=["integrated agreement", "merger clause", "ambiguity exception", "fraud or misrepresentation", "course of dealing"],
                difficulty=4,
            ),
            TutorQuestion(
                question="When is specific performance available as a remedy for breach of contract? When is it unavailable?",
                hint="Think about what types of contracts are uniquely suited for this remedy.",
                expected_concepts=["unique subject matter", "land", "inadequate legal remedy", "personal services exception", "feasibility of supervision"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between a condition precedent and a condition subsequent? Provide an example of each.",
                hint="Consider the timing of when the condition must occur relative to the parties' obligations.",
                expected_concepts=["condition precedent", "condition subsequent", "triggering event", "obligation to perform", "forfeiture"],
                difficulty=3,
            ),
            TutorQuestion(
                question="Explain the doctrine of anticipatory repudiation. When can the non-breaching party treat the contract as breached?",
                hint="This doctrine applies when one party signals they will not perform before performance is due.",
                expected_concepts=["anticipatory repudiation", "unequivocal statement", "prospective inability to perform", "immediate right to sue", "retraction"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What constitutes a material breach versus a minor breach? How does the distinction affect the non-breaching party's remedies?",
                hint="The distinction turns on how severely the breach undermines the contract's purpose.",
                expected_concepts=["material breach", "minor breach", "substantial performance", "right to suspend performance", "damages measurement"],
                difficulty=3,
            ),
            TutorQuestion(
                question="How does the doctrine of impossibility differ from impracticability and frustration of purpose? When are courts likely to excuse performance?",
                hint="All three doctrines address events that make performance difficult, but they have different standards.",
                expected_concepts=["objective impossibility", "commercial impracticability", "frustration of purpose", "force majeure", "supervening event", "UCC 2-615"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the mailbox rule and when does it apply? How does it differ from the receipt rule?",
                hint="This rule determines when acceptance is effective in contract formation.",
                expected_concepts=["mailbox rule", "dispatch rule", "receipt rule", "acceptance by mail", "improper means of communication"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the three types of remedies available for breach of contract? Explain when each is appropriate.",
                hint="Think about the different goals of contract remedies.",
                expected_concepts=["legal remedies", "expectation damages", "reliance damages", "restitution", "equitable remedies", "specific performance"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the duty of good faith and fair dealing? Does it apply to all contracts? Provide an example of a violation.",
                hint="This implied duty exists in every contract under the UCC and common law.",
                expected_concepts=["good faith", "fair dealing", "UCC 1-304", "implied covenant", "discretion in performance"],
                difficulty=3,
            ),
            TutorQuestion(
                question="How do liquidated damages clauses differ from penalty clauses? When will a court enforce a liquidated damages provision?",
                hint="The key is whether the clause is a reasonable estimate of damages or a punitive measure.",
                expected_concepts=["liquidated damages", "penalty clause", "reasonable forecast", "actual damages", "unconscionability"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between an assignment and a delegation? Can all contractual rights be assigned and duties delegated?",
                hint="Consider whether rights, duties, or both are being transferred.",
                expected_concepts=["assignment of rights", "delegation of duties", "novation", "personal services exception", "material change in duties"],
                difficulty=3,
            ),
        ],
    },
    "torts": {
        "name": "Torts",
        "description": "Civil wrongs and the legal remedies available to injured parties.",
        "questions": [
            TutorQuestion(
                question="What are the four elements of a negligence claim?",
                hint="Consider what a plaintiff must prove to establish negligence.",
                expected_concepts=["duty", "breach", "causation", "actual cause", "proximate cause", "damages"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the reasonable person standard and how does it apply in negligence cases?",
                hint="This is the objective standard used to evaluate the defendant's conduct.",
                expected_concepts=["reasonable person", "objective standard", "ordinary care", "foreseeability", "community standards"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between actual cause (cause in fact) and proximate cause (legal cause)?",
                hint="Think about the 'but for' test versus foreseeability of harm.",
                expected_concepts=["but for test", "substantial factor", "foreseeability", "direct cause", "intervening cause", "superseding cause"],
                difficulty=2,
            ),
            TutorQuestion(
                question="Explain the doctrine of res ipsa loquitur and when it can be used to establish negligence.",
                hint="This doctrine allows an inference of negligence from the nature of the accident itself.",
                expected_concepts=["res ipsa loquitur", "exclusive control", "ordinarily does not happen without negligence", "inference of negligence", "burden shifting"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between contributory negligence and comparative negligence? Which approach do most states follow?",
                hint="Contributory negligence is an all-or-nothing bar, while comparative negligence apportions fault.",
                expected_concepts=["contributory negligence", "comparative negligence", "pure comparative fault", "modified comparative fault", "last clear chance"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is strict liability and when does it apply? How does it differ from negligence?",
                hint="Strict liability does not require proof of fault or unreasonable conduct.",
                expected_concepts=["abnormally dangerous activities", "product liability", "defective product", "failure to warn", "design defect"],
                difficulty=3,
            ),
            TutorQuestion(
                question="Explain the difference between an intentional tort and a negligence tort. Provide an example of each.",
                hint="Intentional torts require a specific mental state; negligence requires a failure to exercise reasonable care.",
                expected_concepts=["intent", "specific intent", "general intent", "transferred intent", "negligence", "reasonable care"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the elements of assault and battery? How do they differ from each other?",
                hint="One requires physical contact, the other requires apprehension of contact.",
                expected_concepts=["assault", "apprehension of harmful contact", "battery", "harmful or offensive contact", "overt act"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'eggshell skull' rule and how does it affect damages in tort cases?",
                hint="This rule addresses the defendant's liability when the plaintiff has a pre-existing vulnerability.",
                expected_concepts=["eggshell skull", "thin skull", "preexisting condition", "unforeseeable extent of harm", "full compensation"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between libel and slander? What defenses are available in a defamation action?",
                hint="Libel is written, slander is spoken — but there are nuances in how damages are treated.",
                expected_concepts=["libel", "slander", "defamation per se", "defamation per quod", "privilege", "opinion defense", "truth defense"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'duty to rescue'? When does the law impose an affirmative duty to act?",
                hint="Generally, there is no duty to rescue — but there are important exceptions.",
                expected_concepts=["special relationship", "undertaking", "creation of peril", "Good Samaritan laws", "no general duty"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the economic loss rule and when does it bar recovery in tort?",
                hint="This rule prevents recovery in tort for purely economic losses in certain circumstances.",
                expected_concepts=["economic loss", "contract vs tort", "personal injury exception", "property damage exception", "privity"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the Firefighter's Rule and what is its rationale?",
                hint="This rule limits the ability of certain public safety officers to recover for injuries sustained on the job.",
                expected_concepts=["Firefighter's Rule", "professional rescuer", "assumption of risk", "inherent danger", "public policy"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'zone of danger' test for negligent infliction of emotional distress?",
                hint="This test limits recovery for emotional distress to those who were physically at risk.",
                expected_concepts=["zone of danger", "physical impact", "physical manifestation", "bystander recovery", "close relative"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between an invitee, a licensee, and a trespasser? How does a landowner's duty differ for each?",
                hint="The duty owed depends on the status of the person entering the land.",
                expected_concepts=["invitee", "licensee", "trespasser", "duty of care", "attractive nuisance", "known dangerous conditions"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'last clear chance' doctrine and how does it mitigate the harshness of contributory negligence?",
                hint="This doctrine allows a negligent plaintiff to recover if the defendant had the final opportunity to avoid the harm.",
                expected_concepts=["last clear chance", "helpless peril", "inattentive plaintiff", "subsequent negligence", "avoidable accident"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is a nuisance claim and how does it differ from trespass? Can the same conduct give rise to both?",
                hint="Nuisance involves interference with use and enjoyment of land, while trespass involves physical invasion.",
                expected_concepts=["private nuisance", "public nuisance", "trespass", "substantial interference", "unreasonable use"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What are the elements of false imprisonment? What must a plaintiff prove to establish this intentional tort?",
                hint="Consider what constitutes a 'confinement' and how it can be accomplished.",
                expected_concepts=["false imprisonment", "intent to confine", "confinement", "awareness of confinement", "actual harm", "privilege"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'wrongful birth' tort and how does it differ from 'wrongful life'? Which jurisdictions recognize these claims?",
                hint="These are related but distinct claims brought by different plaintiffs.",
                expected_concepts=["wrongful birth", "wrongful life", "wrongful conception", "parent plaintiff", "child plaintiff", "special damages"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the scope of employment test for vicarious liability (respondeat superior)? When is an employer liable for an employee's torts?",
                hint="The key question is whether the employee was acting within the scope of their employment.",
                expected_concepts=["respondeat superior", "scope of employment", "frolic and detour", "intentional torts by employees", "independent contractor exception"],
                difficulty=3,
            ),
        ],
    },
    "civil_procedure": {
        "name": "Civil Procedure",
        "description": "The rules and standards governing civil litigation in federal courts.",
        "questions": [
            TutorQuestion(
                question="What is subject matter jurisdiction and why is it important?",
                hint="This is the court's authority to hear a particular type of case.",
                expected_concepts=["federal question jurisdiction", "diversity jurisdiction", "amount in controversy", "complete diversity", "28 USC 1331"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between general jurisdiction and specific jurisdiction in personal jurisdiction analysis?",
                hint="The distinction turns on how closely the defendant's contacts relate to the plaintiff's claims.",
                expected_concepts=["general jurisdiction", "specific jurisdiction", "continuous and systematic contacts", "minimum contacts", "relatedness"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the requirements for diversity jurisdiction under 28 USC 1332?",
                hint="Diversity jurisdiction requires both diversity of citizenship and a minimum amount in controversy.",
                expected_concepts=["complete diversity", "amount in controversy", "$75,000", "citizenship of individuals", "citizenship of corporations"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Erie doctrine and how does it affect which law a federal court applies in diversity cases?",
                hint="Erie requires federal courts to apply state substantive law in diversity cases.",
                expected_concepts=["Erie doctrine", "substantive law", "procedural law", "vertical choice of law", "outcome-determinative test"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a motion to dismiss for failure to state a claim (Rule 12(b)(6)) and a motion for summary judgment (Rule 56)?",
                hint="One tests the legal sufficiency of the pleadings; the other tests whether there are factual disputes requiring a trial.",
                expected_concepts=["12(b)(6)", "failure to state a claim", "summary judgment", "genuine dispute", "material fact", "pleading stage vs discovery stage"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'minimum contacts' test for personal jurisdiction and which Supreme Court case established it?",
                hint="This test was established in a landmark 1945 case involving a shoe company.",
                expected_concepts=["International Shoe", "minimum contacts", "fair play and substantial justice", "purposeful availment", "traditional notions of fair play"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is claim preclusion (res judicata) and what are its requirements?",
                hint="This doctrine bars re-litigation of claims that were or could have been litigated.",
                expected_concepts=["res judicata", "final judgment on the merits", "same parties", "same claim", "same transaction or occurrence"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between issue preclusion (collateral estoppel) and claim preclusion (res judicata)?",
                hint="Issue preclusion bars re-litigation of specific issues, while claim preclusion bars entire claims.",
                expected_concepts=["collateral estoppel", "res judicata", "actually litigated", "necessary to the judgment", "mutuality vs non-mutuality"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the standard for pleading a claim under Federal Rule of Civil Procedure 8? How did Twombly and Iqbal change the pleading standard?",
                hint="The 'notice pleading' standard was modified by two Supreme Court cases in 2007 and 2009.",
                expected_concepts=["FRCP 8", "plausibility standard", "Twombly", "Iqbal", "facial plausibility", "formulaic recitation"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is removal jurisdiction and when can a defendant remove a case from state court to federal court?",
                hint="Removal allows a defendant to move a case from state to federal court under certain conditions.",
                expected_concepts=["removal", "28 USC 1441", "diversity removal", "federal question removal", "forum defendant rule", "one-year limit"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the scope of discovery under FRCP 26? What limits exist on what parties can discover?",
                hint="Discovery is broad but not unlimited — there are important protections and proportionality limits.",
                expected_concepts=["FRCP 26(b)(1)", "relevance", "proportionality", "privilege", "work product doctrine", "ESI"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a permissive counterclaim and a compulsory counterclaim under FRCP 13?",
                hint="Compulsory counterclaims arise from the same transaction; permissive ones do not.",
                expected_concepts=["compulsory counterclaim", "permissive counterclaim", "same transaction or occurrence", "waiver", "FRCP 13(a)", "FRCP 13(b)"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the harmless error standard and how does it affect appellate review of trial court decisions?",
                hint="Not every error by the trial court warrants reversal on appeal.",
                expected_concepts=["harmless error", "prejudicial error", "substantial right", "FRCP 61", "reversible error"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a jury trial right under the Seventh Amendment and a bench trial? Which cases get a jury?",
                hint="The Seventh Amendment preserves the right to a jury trial in certain civil cases.",
                expected_concepts=["Seventh Amendment", "jury trial", "bench trial", "legal vs equitable claims", "common law threshold", "jury demand"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the pre-trial conference and what is its purpose under FRCP 16?",
                hint="This is a key case management tool that helps courts manage their dockets and streamline proceedings.",
                expected_concepts=["FRCP 16", "pretrial conference", "scheduling order", "case management", "settlement conference", "pretrial order"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'full faith and credit' doctrine and how does it apply to judgments from other states?",
                hint="This constitutional doctrine requires states to recognize and enforce judgments from other states.",
                expected_concepts=["Full Faith and Credit Clause", "Article IV", "sister state judgments", "finality", "jurisdictional challenge"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is interpleader and when is it available?",
                hint="Interpleader allows a stakeholder to force competing claimants to litigate their claims in a single action.",
                expected_concepts=["interpleader", "stakeholder", "Rule 22", "statutory interpleader", "28 USC 1335", "minimal diversity"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the standard for granting a preliminary injunction? How does it differ from a permanent injunction?",
                hint="Preliminary injunctions are temporary and require a showing of irreparable harm.",
                expected_concepts=["preliminary injunction", "irreparable harm", "likelihood of success", "balance of equities", "public interest", "temporary restraining order"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is forum non conveniens and when is it properly invoked?",
                hint="This doctrine allows a court to dismiss a case when another forum is substantially more appropriate.",
                expected_concepts=["forum non conveniens", "alternative forum", "private interest factors", "public interest factors", "strong presumption in favor of plaintiff's choice"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the law of the case doctrine and how does it differ from stare decisis?",
                hint="This doctrine governs the binding effect of rulings within a single case, not across different cases.",
                expected_concepts=["law of the case", "stare decisis", "same case", "binding on remand", "clear error exception"],
                difficulty=4,
            ),
        ],
    },
    "constitutional_law": {
        "name": "Constitutional Law",
        "description": "The structure of government, federal power, and individual rights under the U.S. Constitution.",
        "questions": [
            TutorQuestion(
                question="What is judicial review and which case established it?",
                hint="This power allows courts to declare laws unconstitutional.",
                expected_concepts=["Marbury v. Madison", "judicial review", "Article III", "supremacy of the Constitution", "justiciability"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between substantive due process and procedural due process?",
                hint="One concerns the content of laws, the other concerns the procedures used to enforce them.",
                expected_concepts=["substantive due process", "procedural due process", "fundamental rights", "notice and hearing", "life, liberty, or property"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the standard of review under the Equal Protection Clause? When does strict scrutiny apply?",
                hint="Different classifications trigger different levels of judicial scrutiny.",
                expected_concepts=["strict scrutiny", "intermediate scrutiny", "rational basis", "suspect classification", "fundamental right", "compelling government interest"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Commerce Clause and how has its interpretation evolved over time?",
                hint="Congress's power to regulate interstate commerce has been interpreted broadly since the New Deal.",
                expected_concepts=["Commerce Clause", "Article I Section 8", "interstate commerce", "substantial effects test", "New Deal", "United States v. Lopez"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'state action' requirement and why is it important for constitutional claims?",
                hint="Most constitutional rights only protect against government action, not private conduct.",
                expected_concepts=["state action", "public function", "entanglement", "symbiotic relationship", "private conduct exception"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between the Establishment Clause and the Free Exercise Clause of the First Amendment?",
                hint="One prohibits government establishment of religion; the other protects individual religious practice.",
                expected_concepts=["Establishment Clause", "Free Exercise Clause", "Lemon test", "coercion test", "neutral law of general applicability"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'clear and present danger' test and how does it limit free speech under the First Amendment?",
                hint="This test balances government interests against free speech rights in cases involving national security.",
                expected_concepts=["clear and present danger", "Schenck v. United States", "Brandenburg test", "imminent lawless action", "incitement"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the Takings Clause and when does a government action constitute a taking requiring just compensation?",
                hint="The Fifth Amendment requires compensation when the government takes private property for public use.",
                expected_concepts=["Takings Clause", "Fifth Amendment", "eminent domain", "public use", "just compensation", "regulatory taking", "Penn Central test"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between the First Amendment protection for commercial speech and political speech?",
                hint="Commercial speech receives less protection than political speech under the First Amendment.",
                expected_concepts=["commercial speech", "political speech", "Central Hudson test", "misleading speech", "government interest"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'wall of separation' between church and state? Is it in the Constitution?",
                hint="This phrase comes from a letter by Thomas Jefferson, not from the Constitution itself.",
                expected_concepts=["wall of separation", "Establishment Clause", "Thomas Jefferson", "accommodation", "endorsement test"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'nondelegation doctrine' and how does it limit Congress's ability to delegate legislative power?",
                hint="This doctrine concerns how much lawmaking power Congress can give to administrative agencies.",
                expected_concepts=["nondelegation doctrine", "intelligible principle", "Article I", "separation of powers", "legislative power"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between the 'necessary and proper' clause and the Commerce Clause?",
                hint="One is an elastic clause that expands Congress's enumerated powers; the other is a specific enumerated power.",
                expected_concepts=["necessary and proper clause", "Commerce Clause", "McCulloch v. Maryland", "implied powers", "enumerated powers"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'independent state grounds' doctrine and how does it affect Supreme Court review of state court decisions?",
                hint="This doctrine limits the Supreme Court's ability to review state court decisions based on state law.",
                expected_concepts=["adequate and independent state grounds", "supreme court review", "state law", "federal question", "final judgment"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the Second Amendment right to bear arms and how has the Supreme Court interpreted it?",
                hint="The Supreme Court has recognized an individual right to keep and bear arms for self-defense.",
                expected_concepts=["Second Amendment", "individual right", "Heller", "McDonald", "reasonable regulation", "self-defense"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Suspension Clause and when can habeas corpus be suspended?",
                hint="This clause protects the writ of habeas corpus, a fundamental safeguard against unlawful detention.",
                expected_concepts=["Suspension Clause", "habeas corpus", "Article I Section 9", "rebellion or invasion", "public safety", "Boumediene"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the 'political question' doctrine and when will courts refuse to hear a case on this basis?",
                hint="Some constitutional questions are committed to the political branches and are not justiciable.",
                expected_concepts=["political question doctrine", "justiciability", "Baker v. Carr", "textually committed", "judicially manageable standards"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between the Fourteenth Amendment's Privileges or Immunities Clause and the Due Process Clause?",
                hint="The Privileges or Immunities Clause was largely nullified by the Slaughter-House Cases.",
                expected_concepts=["Privileges or Immunities Clause", "Due Process Clause", "Slaughter-House Cases", "incorporation doctrine", "fundamental rights"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the 'effects test' for standing and how does it differ from the 'zone of interests' test?",
                hint="Standing requires a concrete injury that is fairly traceable to the defendant's conduct and redressable by the court.",
                expected_concepts=["standing", "injury in fact", "traceability", "redressability", "zone of interests", "prudential standing"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the Third Amendment and why is it rarely litigated?",
                hint="This amendment concerns the quartering of soldiers in private homes.",
                expected_concepts=["Third Amendment", "quartering soldiers", "rarely litigated", "historical context", "privacy implications"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between the 'incorporation' of the Bill of Rights against the states through the Due Process Clause and through the Privileges or Immunities Clause?",
                hint="The Slaughter-House Cases effectively limited incorporation to the Due Process Clause.",
                expected_concepts=["selective incorporation", "Due Process Clause", "Privileges or Immunities Clause", "Slaughter-House Cases", "fundamental fairness"],
                difficulty=4,
            ),
        ],
    },
    "criminal_law": {
        "name": "Criminal Law",
        "description": "Substantive criminal law, including elements of crimes, defenses, and principles of liability.",
        "questions": [
            TutorQuestion(
                question="What are the four elements of a crime?",
                hint="Consider the physical and mental components required for criminal liability.",
                expected_concepts=["actus reus", "mens rea", "concurrence", "causation", "harm"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between general intent and specific intent?",
                hint="Some crimes require intent to commit the act; others require intent to achieve a specific result.",
                expected_concepts=["general intent", "specific intent", "purpose", "knowledge", "Model Penal Code"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the mistake of fact defense and when does it apply? How does it differ from mistake of law?",
                hint="One type of mistake can negate mens rea; the other generally cannot.",
                expected_concepts=["mistake of fact", "mistake of law", "mens rea", "reasonable mistake", "honest mistake"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between murder and manslaughter?",
                hint="The distinction turns on the presence or absence of malice aforethought.",
                expected_concepts=["malice aforethought", "premeditation", "heat of passion", "provocation", "involuntary manslaughter", "voluntary manslaughter"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Model Penal Code's approach to grading criminal attempts compared to the common law approach?",
                hint="The MPC and common law differ in how they define and punish attempts.",
                expected_concepts=["substantial step", "dangerous proximity", "MPC 5.01", "preparation vs attempt", "abandonment defense"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a felony murder rule and a misdemeanor manslaughter rule?",
                hint="Both rules impute liability for deaths that occur during the commission of certain crimes, but they apply to different categories of crimes.",
                expected_concepts=["felony murder", "misdemeanor manslaughter", "inherently dangerous felony", "independent felony", "in furtherance of the felony"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the defense of insanity and how does it differ from incompetency to stand trial?",
                hint="Insanity goes to guilt; incompetency goes to the ability to participate in the proceedings.",
                expected_concepts=["M'Naghten rule", "irresistible impulse", "Model Penal Code test", "Durham test", "incompetency", "guilty but mentally ill"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between larceny, robbery, and burglary?",
                hint="These property crimes differ based on the use of force, the presence of a structure, and the type of property taken.",
                expected_concepts=["larceny", "trespassory taking", "robbery", "force or intimidation", "burglary", "breaking and entering"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'year and a day rule' and how does it apply to homicide cases?",
                hint="This common law rule has been modified or abolished in most jurisdictions.",
                expected_concepts=["year and a day rule", "causation", "intervening cause", "modern reforms", "death requirement"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between an accessory before the fact and an accessory after the fact?",
                hint="The distinction depends on when the person becomes involved in relation to the crime.",
                expected_concepts=["accessory before the fact", "accessory after the fact", "principal", "accomplice", "aiding and abetting", "conspiracy"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the entrapment defense and what are the two tests courts use to determine whether entrapment occurred?",
                hint="Entrapment requires government inducement of a crime that the defendant was not predisposed to commit.",
                expected_concepts=["entrapment", "subjective test", "objective test", "predisposition", "government inducement", "Sherman test"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'consent' defense in criminal law? When does consent negate criminal liability?",
                hint="Consent is not a defense to all crimes — it depends on the nature of the offense and public policy.",
                expected_concepts=["consent", "effective consent", "incapacity to consent", "fraud", "public policy limitations"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Pinkerton doctrine and how does it impose liability for the acts of co-conspirators?",
                hint="This doctrine extends liability to all members of a conspiracy for foreseeable crimes committed in furtherance of the conspiracy.",
                expected_concepts=["Pinkerton", "conspiracy", "foreseeability", "in furtherance of", "withdrawal from conspiracy"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between first-degree murder and second-degree murder?",
                hint="First-degree murder requires premeditation and deliberation; second-degree murder does not.",
                expected_concepts=["premeditation", "deliberation", "first-degree murder", "second-degree murder", "malice aforethought"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the necessity defense and when is it available? How does it differ from duress?",
                hint="Necessity involves choosing the lesser of two evils; duress involves coercion by another person.",
                expected_concepts=["necessity", "choice of evils", "imminent harm", "duress", "coercion by threat", "homicide exception"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'eggshell skull' rule in criminal law and how does it affect causation?",
                hint="This rule makes a defendant liable for the full extent of harm even if the victim was unusually vulnerable.",
                expected_concepts=["eggshell skull", "thin skull", "causation", "unforeseeable harm", "take your victim as you find them"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between rape and statutory rape? Is consent a defense to statutory rape?",
                hint="Statutory rape focuses on the age of the victim, not their actual consent.",
                expected_concepts=["rape", "statutory rape", "age of consent", "strict liability", "reasonable mistake of age"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'defense of property' privilege? When is deadly force justified to protect property?",
                hint="The use of deadly force to protect property is generally prohibited, with limited exceptions.",
                expected_concepts=["defense of property", "deadly force", "nondeadly force", "castle exception", "spring guns", "fresh pursuit"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'corpus delicti' rule and why is it important in criminal prosecutions?",
                hint="This rule requires independent evidence that a crime occurred before a confession can be used.",
                expected_concepts=["corpus delicti", "independent evidence", "confession", "body of the crime", "corroboration rule"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a simple assault and aggravated assault? What factors elevate an assault to aggravated assault?",
                hint="Aggravated assault involves additional factors such as use of a weapon or intent to commit a serious felony.",
                expected_concepts=["simple assault", "aggravated assault", "deadly weapon", "serious bodily injury", "intent to commit a felony"],
                difficulty=2,
            ),
        ],
    },
    "property": {
        "name": "Property",
        "description": "The law of real and personal property, including estates, land transfers, and landlord-tenant relationships.",
        "questions": [
            TutorQuestion(
                question="What is the difference between real property and personal property?",
                hint="Real property is land and things attached to it; personal property is everything else.",
                expected_concepts=["real property", "personal property", "fixtures", "chattels", "emblements"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between a fee simple absolute and a life estate?",
                hint="One lasts forever; the other lasts for the duration of someone's life.",
                expected_concepts=["fee simple absolute", "life estate", "remainder", "reversion", "waste"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the elements of adverse possession?",
                hint="Adverse possession allows a trespasser to gain title to land if certain conditions are met.",
                expected_concepts=["actual possession", "open and notorious", "hostile", "exclusive", "continuous", "statutory period"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between a joint tenancy and a tenancy in common?",
                hint="The key difference is the right of survivorship.",
                expected_concepts=["joint tenancy", "right of survivorship", "four unities", "tenancy in common", "severance"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the Rule Against Perpetuities and why is it considered one of the most complex rules in property law?",
                hint="This rule limits the duration of future interests in property to prevent remote control by the dead.",
                expected_concepts=["Rule Against Perpetuities", "lives in being", "21 years", "vesting", "wait-and-see", "uniform statutory rule"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between an easement and a license?",
                hint="One creates a permanent property interest; the other is a revocable permission.",
                expected_concepts=["easement", "license", "revocability", "appurtenant", "in gross", "creation by necessity"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the implied warranty of habitability and when does it apply in landlord-tenant law?",
                hint="This warranty requires landlords to maintain rental premises in a habitable condition.",
                expected_concepts=["implied warranty of habitability", "fit for human habitation", "constructive eviction", "repair and deduct", "retaliatory eviction"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a covenant and an equitable servitude?",
                hint="Covenants are promises enforced by damages; equitable servitudes are enforced by injunction.",
                expected_concepts=["covenant", "equitable servitude", "touch and concern", "horizontal privity", "vertical privity", "notice"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the 'finders keepers' rule in property law? When does a finder获得 title to lost or mislaid property?",
                hint="The finder's rights depend on whether the property is lost, mislaid, or abandoned.",
                expected_concepts=["lost property", "mislaid property", "abandoned property", "true owner", "prior possessor", "constructive possession"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a determinable fee and a fee simple subject to condition subsequent?",
                hint="Both are defeasible fees, but they differ in how the estate terminates and who has the right of entry.",
                expected_concepts=["fee simple determinable", "possibility of reverter", "fee simple subject to condition subsequent", "right of entry", "limitation vs condition"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the 'nuisance' exception to the adverse possession rule?",
                hint="This exception allows a landowner to interrupt the adverse possession period by bringing a nuisance action.",
                expected_concepts=["nuisance exception", "interruption of possession", "consent", "permission", "tacking"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is eminent domain and what is the 'public use' requirement?",
                hint="The government can take private property for public use, but must pay just compensation.",
                expected_concepts=["eminent domain", "public use", "just compensation", "Kelo v. New London", "economic development"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between a mortgage and a deed of trust?",
                hint="Both secure a debt with real property, but they involve different parties and foreclosure procedures.",
                expected_concepts=["mortgage", "deed of trust", "promissory note", "foreclosure", "equity of redemption", "strict foreclosure"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'waste' doctrine and how does it apply to life tenants and landlords?",
                hint="Waste occurs when someone with limited ownership rights damages the property.",
                expected_concepts=["voluntary waste", "permissive waste", "ameliorative waste", "life tenant", "landlord", "fixtures"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a lease and a license?",
                hint="A lease creates a property interest; a license is merely permission to use property.",
                expected_concepts=["lease", "license", "exclusive possession", "term of years", "periodic tenancy", "tenancy at will"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is a restrictive covenant and how is it enforced?",
                hint="Restrictive covenants limit how property can be used and are typically enforced by other property owners.",
                expected_concepts=["restrictive covenant", "equitable servitude", "running with the land", "notice", "changed circumstances"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'relation back' doctrine in property law and how does it affect priority of interests?",
                hint="This doctrine affects the priority of recorded interests and unrecorded interests.",
                expected_concepts=["relation back", "recording acts", "race statute", "notice statute", "race-notice statute", "bona fide purchaser"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is a future interest and what types of future interests are recognized at common law?",
                hint="Future interests are present ownership rights that give the holder the right to possession in the future.",
                expected_concepts=["reversion", "remainder", "executory interest", "vested remainder", "contingent remainder", "Rule Against Perpetuities"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is a bailment and what are the duties of a bailee?",
                hint="A bailment occurs when one person temporarily holds another person's personal property.",
                expected_concepts=["bailment", "bailee", "bailor", "standard of care", "gratuitous bailment", "mutual benefit bailment"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'ancient documents' rule in property law and how does it affect the admissibility of property records?",
                hint="This rule allows certain old documents to be admitted as evidence without proof of authenticity.",
                expected_concepts=["ancient documents", "20 years", "recording acts", "chain of title", "self-authentication"],
                difficulty=3,
            ),
        ],
    },
    "evidence": {
        "name": "Evidence",
        "description": "The rules governing what evidence can be admitted in court and how it can be used.",
        "questions": [
            TutorQuestion(
                question="What is relevance and why is it the foundation of all evidence?",
                hint="Evidence must be relevant to be admissible; irrelevant evidence is never admissible.",
                expected_concepts=["relevant evidence", "probative", "material", "FRE 401", "FRE 402"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the difference between direct evidence and circumstantial evidence?",
                hint="Direct evidence proves a fact directly; circumstantial evidence requires an inference.",
                expected_concepts=["direct evidence", "circumstantial evidence", "inference", "sufficiency", "weight of evidence"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is hearsay and why is it generally inadmissible?",
                hint="Hearsay involves an out-of-court statement offered to prove the truth of the matter asserted.",
                expected_concepts=["hearsay", "out-of-court statement", "declarant", "truth of the matter asserted", "FRE 801", "FRE 802"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the major exceptions to the hearsay rule?",
                hint="There are two categories of exceptions: those where the declarant is available and those where the declarant is unavailable.",
                expected_concepts=["excited utterance", "present sense impression", "business records", "dying declaration", "statement against interest", "forfeiture by wrongdoing"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between lay opinion testimony and expert opinion testimony?",
                hint="Lay testimony is based on personal perception; expert testimony is based on specialized knowledge.",
                expected_concepts=["lay opinion", "FRE 701", "expert testimony", "FRE 702", "Daubert standard", "reliable methodology"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the character evidence rule and when is character evidence admissible?",
                hint="Character evidence is generally inadmissible to prove conduct, but there are important exceptions.",
                expected_concepts=["character evidence", "FRE 404", "propensity", "MIMIC exception", "criminal defendant's character", "victim's character"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the best evidence rule and when does it apply?",
                hint="This rule requires the original writing, recording, or photograph to prove its contents.",
                expected_concepts=["best evidence rule", "original document", "FRE 1002", "duplicate", "testimony about document"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the privilege against self-incrimination and who can invoke it?",
                hint="This privilege is protected by the Fifth Amendment and applies to testimonial evidence.",
                expected_concepts=["Fifth Amendment", "self-incrimination", "testimonial evidence", "corporations", "immunity"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between a voir dire of a witness and a direct examination?",
                hint="Voir dire is a preliminary examination to determine qualifications; direct examination is the main questioning.",
                expected_concepts=["voir dire", "direct examination", "cross examination", "witness competency", "leading questions"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the attorney-client privilege and what communications are protected?",
                hint="This privilege protects confidential communications between attorney and client for legal advice.",
                expected_concepts=["attorney-client privilege", "confidential communication", "legal advice", "waiver", "crime-fraud exception"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the authentication requirement for evidence and how can evidence be authenticated?",
                hint="Evidence must be authenticated before it can be admitted. There are many methods of authentication.",
                expected_concepts=["authentication", "FRE 901", "self-authentication", "FRE 902", "witness testimony", "distinctive characteristics"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between a motion in limine and an objection at trial?",
                hint="One is made before trial; the other is made during trial.",
                expected_concepts=["motion in limine", "objection", "pretrial ruling", "preserving error", "curative instruction"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'silent witness' theory for admitting photographic evidence?",
                hint="This theory allows photos to be admitted as substantive evidence when they speak for themselves.",
                expected_concepts=["silent witness theory", "photographic evidence", "accurate representation", "foundation", "relevance"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a stipulation and a judicial notice?",
                hint="One is agreed to by the parties; the other is recognized by the court without proof.",
                expected_concepts=["stipulation", "judicial notice", "adjudicative facts", "FRE 201", "indisputable fact"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'impeachment' of a witness and what methods are available?",
                hint="Impeachment attacks the credibility of a witness's testimony.",
                expected_concepts=["impeachment", "prior inconsistent statement", "bias", "character for truthfulness", "criminal conviction", "FRE 607-609"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a leading question and a non-leading question? When are leading questions permitted?",
                hint="Leading questions suggest the answer; they are generally prohibited on direct examination but allowed on cross.",
                expected_concepts=["leading question", "suggestive", "direct examination", "cross examination", "hostile witness", "preliminary matters"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is the 'plain view' doctrine and when does it apply?",
                hint="This doctrine allows police to seize evidence visible in plain view without a warrant.",
                expected_concepts=["plain view", "warrantless seizure", "lawful vantage point", "immediately apparent", "inadvertent discovery"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'exclusionary rule' and what is its purpose?",
                hint="This rule prevents the government from using evidence obtained in violation of the Constitution.",
                expected_concepts=["exclusionary rule", "deterrence", "Fourth Amendment", "fruit of the poisonous tree", "good faith exception"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a photograph used as demonstrative evidence and one used as substantive evidence?",
                hint="Demonstrative evidence illustrates testimony; substantive evidence proves a fact directly.",
                expected_concepts=["demonstrative evidence", "substantive evidence", "illustrative", "probativeness", "foundation requirements"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'business records' hearsay exception and what are its requirements?",
                hint="This exception allows the admission of regularly kept business records even though they are hearsay.",
                expected_concepts=["business records", "regularly conducted activity", "FRE 803(6)", "custodian of records", "trustworthiness", "lack of trustworthiness exception"],
                difficulty=3,
            ),
        ],
    },
    "corporations": {
        "name": "Corporations",
        "description": "Business entity formation, governance, fiduciary duties, and shareholder rights.",
        "questions": [
            TutorQuestion(
                question="What are the key differences between a corporation and an LLC?",
                hint="Both provide limited liability, but differ in management structure, taxation, and formalities.",
                expected_concepts=["limited liability", "double taxation", "pass-through taxation", "management structure", "corporate formalities", "operating agreement"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What are the fiduciary duties owed by corporate directors and officers?",
                hint="Directors and officers must act in the best interests of the corporation and its shareholders.",
                expected_concepts=["duty of care", "duty of loyalty", "business judgment rule", "good faith", "conflict of interest"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the business judgment rule and how does it protect corporate directors?",
                hint="This rule creates a presumption that directors acted in good faith and with due care.",
                expected_concepts=["business judgment rule", "presumption", "informed decision", "good faith", "honest belief", "waste"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What are the requirements for forming a corporation under state law?",
                hint="Formation typically involves filing certain documents with the state and establishing basic corporate structures.",
                expected_concepts=["articles of incorporation", "bylaws", "incorporator", "registered agent", "board of directors", "authorized shares"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is 'piercing the corporate veil' and when will courts disregard the corporate entity?",
                hint="Courts may pierce the veil when a corporation is used to commit fraud or is merely an alter ego.",
                expected_concepts=["piercing the corporate veil", "alter ego", "undercapitalization", "fraud", "commingling of assets", "instrumentality"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a de jure corporation and a de facto corporation?",
                hint="One is formed in strict compliance with the law; the other exists in fact but not in full legal form.",
                expected_concepts=["de jure corporation", "de facto corporation", "good faith attempt", "colorable compliance", "corporation by estoppel"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What are the different types of shares a corporation can issue and what rights do they carry?",
                hint="Shares can have different rights, preferences, and privileges attached to them.",
                expected_concepts=["common stock", "preferred stock", "voting rights", "dividend rights", "liquidation preference", "authorized vs issued shares"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the difference between a director's conflict of interest transaction and a corporate opportunity?",
                hint="One involves a transaction between the director and the corporation; the other involves a business opportunity that belongs to the corporation.",
                expected_concepts=["conflict of interest", "interested director transaction", "corporate opportunity", "fairness test", "disclosure", "independent director approval"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What are the requirements for a valid shareholder derivative suit?",
                hint="A derivative suit is brought by a shareholder on behalf of the corporation, not for the shareholder's personal benefit.",
                expected_concepts=["derivative suit", "demand requirement", "demand futility", "contemporaneous ownership", "standing", "special litigation committee"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between a merger and an acquisition?",
                hint="One involves two corporations combining; the other involves one corporation purchasing another.",
                expected_concepts=["merger", "acquisition", "shareholder vote", "appraisal rights", "cash-out merger", "tender offer"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'ultra vires' doctrine and how does it apply to modern corporations?",
                hint="This doctrine concerns acts that are beyond a corporation's stated purposes.",
                expected_concepts=["ultra vires", "corporate purpose", "ratification", "shareholder injunction", "attorney general action"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between a close corporation and a publicly held corporation?",
                hint="These differ in the number of shareholders, how shares are traded, and the level of formality required.",
                expected_concepts=["closely held corporation", "publicly held corporation", "shareholder agreement", "oppression", "restrictions on transfer", "SEC requirements"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'duty of care' for corporate directors and what standard is used to evaluate director conduct?",
                hint="Directors must exercise the care that an ordinarily prudent person would exercise in similar circumstances.",
                expected_concepts=["duty of care", "ordinarily prudent person", "informed decision", "reliance on experts", "oversight responsibility", "Caremark claim"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the 'duty of loyalty' and what types of transactions can violate it?",
                hint="This duty requires directors to act in the best interests of the corporation rather than their personal interests.",
                expected_concepts=["conflict of interest", "corporate opportunity", "self-dealing", "compensation", "competition with the corporation"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is the difference between cumulative voting and straight voting for directors?",
                hint="These voting methods affect how minority shareholders can elect directors.",
                expected_concepts=["cumulative voting", "straight voting", "minority representation", "vote multiplication", "statutory vs permissive"],
                difficulty=2,
            ),
            TutorQuestion(
                question="What is the 'appraisal right' and when can a shareholder exercise it?",
                hint="This right allows dissenting shareholders to receive fair value for their shares in certain transactions.",
                expected_concepts=["appraisal right", "dissenter's rights", "fair value", "market exception", "fundamental change"],
                difficulty=3,
            ),
            TutorQuestion(
                question="What is a 'poison pill' and how does it work as a defensive measure against hostile takeovers?",
                hint="This is a shareholder rights plan designed to make a hostile takeover prohibitively expensive.",
                expected_concepts=["poison pill", "shareholder rights plan", "flip-in", "flip-over", "triggering event", "board discretion"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the difference between a director and an officer of a corporation?",
                hint="Directors set policy and oversee management; officers execute the day-to-day operations.",
                expected_concepts=["board of directors", "officers", "election", "appointment", "fiduciary duties", "management role"],
                difficulty=1,
            ),
            TutorQuestion(
                question="What is a 'blank check' preferred stock and why might a corporation authorize it?",
                hint="This type of stock gives the board discretion to set the terms of the preferred shares.",
                expected_concepts=["blank check preferred", "board discretion", "antitakeover device", "designation rights", "series creation"],
                difficulty=4,
            ),
            TutorQuestion(
                question="What is the 'revlon duty' and when does it apply?",
                hint="This duty arises when a corporation is being sold and the board's role shifts from protecting the corporation to maximizing shareholder value.",
                expected_concepts=["Revlon duty", "change of control", "maximize shareholder value", "auction duty", "Revlon mode", "best price"],
                difficulty=4,
            ),
        ],
    },
}
