FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install uv

COPY backend/pyproject.toml ./

RUN uv sync

COPY backend/ .
COPY catalog.json ./
COPY templates ./templates

EXPOSE 8000

CMD [".venv/bin/python3", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]